# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('head_style', models.CharField(choices=[('Normal', 'Normal'), ('Wacky', 'Wacky')], default='Normal', max_length=500)),
                ('body_style', models.CharField(choices=[('Black Shirt', 'Black Shirt'), ('Blue Shirt', 'Blue Shirt'), ('Green Shirt', 'Green Shirt'), ('Grey Shirt', 'Grey Shirt'), ('Red Shirt', 'Red Shirt')], default='Black Shirt', max_length=500)),
                ('arm_style', models.CharField(choices=[('Ninja Shirt', 'Ninja Shirt'), ('Black T-Shirt', 'Black T-Shirt'), ('Blue T-Shirt', 'Blue T-Shirt'), ('Red T-Shirt', 'Red T-Shirt'), ('Green T-Shirt', 'Green T-Shirt'), ('Sleeveless T-Shirt', 'Sleeveless T-Shirt')], default='Black T-Shirt', max_length=500)),
                ('leg_style', models.CharField(choices=[('Blue Pants', 'Blue Pants'), ('Denim Plants', 'Denim Plants'), ('Black Shorts', 'Black Shorts'), ('Brown Shorts', 'Brown Shorts'), ('Denim Shorts', 'Denim Shorts')], default='Blue Pants', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creature_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to='main_app.Creature')),
                ('creature_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='main_app.Creature')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('username', models.CharField(default='USERNAME', max_length=45)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('description', models.TextField(default='DESCRIPTION', max_length=500)),
                ('number_created', models.IntegerField(default=0)),
                ('traded', models.IntegerField(default=0)),
                ('owned', models.IntegerField(default=0)),
                ('last_log', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('userManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='user_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='main_app.User'),
        ),
        migrations.AddField(
            model_name='trade',
            name='user_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main_app.User'),
        ),
        migrations.AddField(
            model_name='creature',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
    ]
