# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('head_style', models.CharField(choices=[('main_app/img/standard.png', 'Normal'), ('main_app/img/wacky.png', 'Wacky')], default='Normal', max_length=500)),
                ('body_style', models.CharField(choices=[('main_app/img/paleblackbody.png', 'Black Shirt'), ('main_app/img/palebluebody.png', 'Blue Shirt'), ('main_app/img/palegreenbody.png', 'Green Shirt'), ('main_app/img/palegreybody.png', 'Grey Shirt'), ('main_app/img/paleredbody.png', 'Red Shirt')], default='Black Shirt', max_length=500)),
                ('arm_style', models.CharField(choices=[('main_app/img/ninja.png', 'Ninja Shirt'), ('main_app/img/paleblackt.png', 'Black T-Shirt'), ('main_app/img/palebluet.png', 'Blue T-Shirt'), ('main_app/img/paleredt.png', 'Red T-Shirt'), ('main_app/img/palegreent.png', 'Green T-Shirt'), ('main_app/img/palesleveless.png', 'Sleeveless T-Shirt')], default='Black T-Shirt', max_length=500)),
                ('leg_style', models.CharField(choices=[('main_app/img/bluepants.png', 'Blue Pants'), ('main_app/img/denimpants.png', 'Denim Plants'), ('main_app/img/paleblackshorts.png', 'Black Shorts'), ('main_app/img/palebrownshorts.png', 'Brown Shorts'), ('main_app/img/bluepants.png', 'Denim Shorts')], default='Blue Pants', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creature_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reveived', to='main_app.Creature')),
                ('creature_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='main_app.Creature')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('username', models.CharField(default='USERNAME', max_length=45)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('description', models.TextField(default='DESCRIPTION', max_length=500)),
                ('number_created', models.IntegerField(default=0)),
                ('traded', models.IntegerField(default=0)),
                ('owned', models.IntegerField(default=0)),
                ('last_log', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('userManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='user_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='main_app.User'),
        ),
        migrations.AddField(
            model_name='trade',
            name='user_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main_app.User'),
        ),
        migrations.AddField(
            model_name='creature',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
    ]
