# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='leg_style',
            field=models.CharField(choices=[('Blue Pants', 'Blue Pants'), ('Denim Plants', 'Denim Pants'), ('Black Shorts', 'Black Shorts'), ('Brown Shorts', 'Brown Shorts'), ('Denim Shorts', 'Denim Shorts')], default='Blue Pants', max_length=500),
        ),
    ]
