# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='arm_style',
            field=models.CharField(choices=[('Ninja Shirt', 'Ninja Shirt'), ('Black T-Shirt', 'Black T-Shirt'), ('Blue T-Shirt', 'Blue T-Shirt'), ('Red T-Shirt', 'Red T-Shirt'), ('Green T-Shirt', 'Green T-Shirt'), ('Sleeveless T-Shirt', 'Sleeveless T-Shirt')], default='Black T-Shirt', max_length=500),
        ),
        migrations.AlterField(
            model_name='creature',
            name='body_style',
            field=models.CharField(choices=[('Black Shirt', 'Black Shirt'), ('Blue Shirt', 'Blue Shirt'), ('Green Shirt', 'Green Shirt'), ('Grey Shirt', 'Grey Shirt'), ('Red Shirt', 'Red Shirt')], default='Black Shirt', max_length=500),
        ),
        migrations.AlterField(
            model_name='creature',
            name='head_style',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Wacky', 'Wacky')], default='Normal', max_length=500),
        ),
        migrations.AlterField(
            model_name='creature',
            name='leg_style',
            field=models.CharField(choices=[('Blue Pants', 'Blue Pants'), ('Denim Plants', 'Denim Plants'), ('Black Shorts', 'Black Shorts'), ('Brown Shorts', 'Brown Shorts'), ('Denim Shorts', 'Denim Shorts')], default='Blue Pants', max_length=500),
        ),
    ]
