# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='USERNAME', max_length=45),
        ),
    ]
