# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20160629_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arm',
            old_name='color',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='body',
            old_name='color',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='head',
            old_name='color',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='leg',
            old_name='color',
            new_name='file_path',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='DESCRIPTION', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='last_log',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='number_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='traded',
            field=models.IntegerField(default=0),
        ),
    ]
