# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20160629_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creature_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to='main_app.Creature')),
                ('creature_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='main_app.Creature')),
            ],
        ),
        migrations.RenameField(
            model_name='arm',
            old_name='color',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='body',
            old_name='color',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='head',
            old_name='color',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='leg',
            old_name='color',
            new_name='file_path',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='DESCRIPTION', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='last_log',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='number_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='traded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='user_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='main_app.User'),
        ),
        migrations.AddField(
            model_name='trade',
            name='user_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main_app.User'),
        ),
    ]
